### PR TITLE
Log info on the upload

### PR DESCRIPTION
**Pull request by GenieTim**
This fixes issue #7.

Also, to speed things up, I added `-P` to get parallel up/downloads.

### CODE REVIEW

**Review by marcauberer — APPROVED** [review]
LGTM

**Comment by GenieTim** [comment]
@marcauberer if you want, you may use my FTP action in the meantime in case you need this feature: https://github.com/GenieTim/ftp-action, replace sebastianpopp/ftp-action@releases/v2 with genietim/ftp-action@releases/v3

**Comment by marcauberer** [comment]
@GenieTim Thank you. I will take a look

**Comment by marcauberer** [comment]
@GenieTim Does not work. It says "Action not found".

**Comment by GenieTim** [comment]
That's unfortunate, dear @marcauberer , and I am very sorry to hear that as well as to have to say that [it works for me](https://github.com/GenieTim/genieblog.ch/blob/aadf21ff9b09acda87422bdcab83086b3c740d45/.github/workflows/publish-posts.yml#L70). Possibly some permission thing since it is "my" action? I would have to do some research on this. 
I could not publish it on the marketplace as-is since I had to rename it, what I did, so now you might find it here: https://github.com/marketplace/actions/ftp-upload-action

**Pull request closed without merging**
